//! Authoring -> Canonical parity with the TypeScript core: every OLL example
//! ships the canonical JSONL that `normalizeAuthoringLesson` produces for the
//! host in examples/manifest.json.
use oll_runtime::authoring::{normalize, Host};
use serde_json::Value;
use std::path::Path;

fn examples() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples")
}

#[test]
fn examples_normalize_like_the_typescript_core() {
    let manifest: Vec<Value> =
        serde_json::from_str(&std::fs::read_to_string(examples().join("manifest.json")).unwrap()).unwrap();
    let mut checked = 0;
    for entry in &manifest {
        let dir = examples().join(entry["name"].as_str().unwrap());
        let (Ok(source), Ok(expected)) = (
            std::fs::read_to_string(dir.join("lesson.authoring.json")),
            std::fs::read_to_string(dir.join("lesson.canonical.jsonl")),
        ) else {
            continue;
        };
        let host = Host {
            lesson_id: entry["lessonId"].as_str().unwrap().into(),
            board_id: entry["boardId"].as_str().unwrap().into(),
            base_revision: entry["baseRevision"].as_i64().unwrap(),
            region_intent: entry["regionIntent"].as_str().unwrap_or("new_topic").into(),
            region_id: entry["regionId"].as_str().map(Into::into),
        };
        let got = normalize(&serde_json::from_str(&source).unwrap(), &host)
            .unwrap_or_else(|e| panic!("{}: {e}", entry["name"]));
        let want: Vec<Value> =
            expected.lines().filter(|l| !l.trim().is_empty()).map(|l| serde_json::from_str(l).unwrap()).collect();
        assert_eq!(got.len(), want.len(), "{}: event count", entry["name"]);
        for (i, (g, w)) in got.iter().zip(&want).enumerate() {
            assert_eq!(g, w, "{}: event {i}", entry["name"]);
        }
        checked += 1;
    }
    assert!(checked >= 8, "only {checked} examples checked");
}

/// A lesson generated by the local learning-coach (octos solo, 2026-10-07):
/// the native materializer matches octos-learn `materializeOllLesson`
/// (fixture produced by the web bundle) and the result plays to the end.
#[test]
fn live_lesson_materializes_like_the_web_and_plays() {
    use oll_runtime::authoring::materialize_jsonl;
    use oll_runtime::session::Session;
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/live");
    let source: Value = serde_json::from_str(&std::fs::read_to_string(dir.join("proportional.authoring.json")).unwrap()).unwrap();
    let host = Host {
        lesson_id: "live-1".into(),
        board_id: "learn-1".into(),
        base_revision: 0,
        region_intent: "new_topic".into(),
        region_id: Some("region:1".into()),
    };
    let jsonl = materialize_jsonl(&source, &host).unwrap();
    let got: Vec<Value> = jsonl.lines().map(|l| serde_json::from_str(l).unwrap()).collect();
    let want: Vec<Value> = std::fs::read_to_string(dir.join("proportional.canonical.jsonl"))
        .unwrap()
        .lines()
        .map(|l| serde_json::from_str(l).unwrap())
        .collect();
    assert_eq!(got, want);
    let mut session = Session::load(&jsonl).unwrap();
    for _ in 0..200 {
        if session.complete() {
            break;
        }
        session.advance_beat().unwrap();
    }
    assert!(session.complete());
}

/// A generated lesson whose Beat replays a start state (`lesson.phase.start`,
/// web beginPhaseTransition): the variables ease to the start values over
/// the brief duration while playing, and the lesson plays to the end.
#[test]
fn phase_start_replays_variables_while_playing() {
    use oll_runtime::authoring::materialize_jsonl;
    use oll_runtime::session::Session;
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/live");
    let source: Value = serde_json::from_str(&std::fs::read_to_string(dir.join("phase-start.authoring.json")).unwrap()).unwrap();
    let host = Host {
        lesson_id: "live-2".into(),
        board_id: "learn-2".into(),
        base_revision: 0,
        region_intent: "new_topic".into(),
        region_id: None,
    };
    let jsonl = materialize_jsonl(&source, &host).unwrap();
    assert!(jsonl.contains("\"lesson.phase.start\""));
    let mut session = Session::load(&jsonl).unwrap();
    session.play().unwrap();
    for _ in 0..20_000 {
        if session.complete() {
            break;
        }
        session.tick(0.05).unwrap();
        if !session.playing {
            session.play().unwrap();
        }
    }
    assert!(session.complete());
}
